#ifndef _PYTHON_INTERFACE_TENSORSWIFT_H
#define _PYTHON_INTERFACE_TENSORSWIFT_H

#define MODULE_NAME tensorswift
#define MODULE_TENSORCLASS_PYTHONNAME "SwiftTensor"
#define MODULE_GENCONTAINER_PYTHONNAME "Data"

#endif